version: "2.4"

services:
  playwright:
    image: order-client-autotests:local
    build: .
    working_dir: /app
    env_file:
      - .env
    environment:
      CI: ${CI}
      PLAYWRIGHT_HEADLESS: ${PLAYWRIGHT_HEADLESS}
      AUTOTEST_ENV: ${AUTOTEST_ENV}
    volumes:
      - ./playwright-report:/app/playwright-report
      - ./test-results:/app/test-results
    command: ["npx", "playwright", "test"]

  smoke:
    image: order-client-autotests:local
    build: .
    working_dir: /app
    env_file:
      - .env
    environment:
      CI: ${CI}
      PLAYWRIGHT_HEADLESS: ${PLAYWRIGHT_HEADLESS}
      AUTOTEST_ENV: ${AUTOTEST_ENV}
    volumes:
      - ./playwright-report:/app/playwright-report
      - ./test-results:/app/test-results
    command: ["npx", "playwright", "test", "--grep", "@smoke"]

  release:
    image: order-client-autotests:local
    build: .
    working_dir: /app
    env_file:
      - .env
    environment:
      CI: ${CI}
      PLAYWRIGHT_HEADLESS: ${PLAYWRIGHT_HEADLESS}
      AUTOTEST_ENV: ${AUTOTEST_ENV}
    volumes:
      - ./playwright-report:/app/playwright-report
      - ./test-results:/app/test-results
    command: ["npx", "playwright", "test", "--grep", "@release"]

  tutor:
    image: order-client-autotests:local
    build: .
    working_dir: /app
    env_file:
      - .env
    environment:
      CI: ${CI}
      PLAYWRIGHT_HEADLESS: ${PLAYWRIGHT_HEADLESS}
      AUTOTEST_ENV: ${AUTOTEST_ENV}
    volumes:
      - ./playwright-report:/app/playwright-report
      - ./test-results:/app/test-results
    command: ["npx", "playwright", "test", "--grep", "@tutor"]

  dev-smoke:
    image: order-client-autotests:local
    build: .
    working_dir: /app
    env_file:
      - .env
    environment:
      CI: ${CI}
      PLAYWRIGHT_HEADLESS: ${PLAYWRIGHT_HEADLESS}
      AUTOTEST_ENV: dev
    volumes:
      - ./playwright-report:/app/playwright-report
      - ./test-results:/app/test-results
    command: ["npx", "playwright", "test", "--grep", "@smoke"]
